setwd(file.path(Sys.getenv('my_dir'),'2021/05/impicit_racial_bias/'))

library(foreign)
library(memisc)
library(plyr)
library(dplyr)

## Loop for..
## 1) Iteratively get all the raw statistical file from 'raw' folder 
## 2) Generate csv file and put under 'cleansed' folder for further processing
#fileNames <- Sys.glob(paste("implicit_bias_project_implicit_harvard_university/race_iat_public/*.", "sav", sep = ""))
#fileNumbers <- seq(fileNames)
#memory.limit(size=407070)
#setwd(file.path(Sys.getenv('my_dir'),'2021/05/impicit_racial_bias/cleaned_datea_race_iat_public/'))
#for (fileNumber in fileNumbers)
#{
#  shortFileName <- tail(strsplit(fileNames[fileNumber],"/")[[1]],1)
#  csvFileName <-  paste("cleaned_datea_race_iat_public/", sub(paste("\\.", "sav", sep = ""), "", shortFileName),".", "csv", sep = "")
#  dataset1 = read.spss(fileNames[fileNumber], to.data.frame=TRUE)

#  if (fileNames == "Race IAT.public.2002-2003.sav|Race IAT.public.2004.sav") {
#    df <- dataset1[,c("D_biep.White_Good_all","country","ethnic")]
#    colnames(df)[which(names(df) == "raceomb")] <- "ethnic"
#    } else if (fileNames == "Race IAT.public.2005.sav|Race IAT.public.2006.sav")  {
#      df <- dataset1[,c("D_biep.White_Good_all","countrycit","countryres","ethnic")] 
#      } else if (fileNames == "Race IAT.public.2017.sav|Race IAT.public.2018.sav|Race IAT.public.2019.sav|Race IAT.public.2020.sav")  {
#        df <- dataset1[,c("D_biep.White_Good_all","countrycit_num","countryres_num","ethnic")] 
#        }else {
#          df <- dataset1[,c("D_biep.White_Good_all","countrycit","countryres","ethnicityomb")]
#        }
#  write.csv(df, csvFileName)
#}

##race = White:6, ethnicity = White:5
###### cleaning the csv files for unwanted entries in countrycit ######
setwd(file.path(Sys.getenv('my_dir'),'2021/05/impicit_racial_bias/cleaned_data_race_iat_public/'))

fileNames <- list.files(path = file.path(getwd()), pattern = "*.csv")
fileNumbers <- seq(fileNames)

for (fileNumber in fileNumbers)
{
  #csvFileName <-  paste(sub(paste("\\.", "csv", sep = ""), "", fileNames[fileNumber]),".", "csv", sep = "")
  df = read.csv(file.path(fileNames[fileNumber]), header=TRUE)
  df2 <- df[!df$countrycit %in% c(". ","  ",".",".   ","    "),]
  ## Remove the white spaces infront of countrycodes ##
  df22 <- data.frame(lapply(df2, trimws))
  ## removing an unwanted column carried over
  cols.dont.want <- "X"
  df3 <- df22[, ! names(df22) %in% cols.dont.want, drop = F]
  xx<-fileNames[fileNumber]
  #xx <- paste(dataloc,"/cleansed/",tail(strsplit(fileNames[fileNumber],"/")[[1]],1),sep="")
  write.csv(df3, xx, row.names=FALSE, quote=FALSE)
}

###### Additional processing for 2015 files and later ######
## Separating 2015 files and later to new format and old format files ##
IAT_2015_format_exception<- function(year){
df <- read.csv(paste0("Race IAT.public.",year,".csv"))
df2 <- df[grepl(pattern="[[:digit:]]", df$countrycit)|grepl(pattern="[[:digit:]]", df$countryres), ]
dfdig <- df2[!grepl(pattern="-9", df2$countrycit), ]
dfalp <- df[grepl(pattern="[[:alpha:]]", df$countrycit) & !grepl(pattern="[[:digit:]]", df$countryres), ]
write.csv(dfdig, file.path(paste0("RaceIAT_public_",year,"_digit.csv")), row.names=FALSE, quote=FALSE)
write.csv(dfalp, file.path(paste0("RaceIAT_public_",year,"_alpha.csv")), row.names=FALSE, quote=FALSE)
#Deleting the old file to replace with the processed file
fn <- file.path(paste0("Race IAT.public.",year,".csv"))
if (file.exists(fn)) file.remove(fn)

###### Merging or mapping the files ######
## Processing the new format files
datafile_year=paste0("RaceIAT_public_",year,"_digit.csv")
df1 <- read.delim(file.path(Sys.getenv('my_dir'),'2021/05/impicit_racial_bias/original_european_map_of_implicit_racial_bias/data/Mapper.txt'))
df11 <- read.delim(file.path(Sys.getenv('my_dir'),'2021/05/impicit_racial_bias/original_european_map_of_implicit_racial_bias/data/Ethnic.txt'))
dfdig <- read.csv(datafile_year, header=TRUE)
(map <- setNames(df1$countrycitcode, df1$countrycit))
if (file.exists(fn)) file.remove(datafile_year)
dfdig[c("countrycit", "countryres")] <- lapply(dfdig[c("countrycit", "countryres")],function(x) map[as.character(x)])
##race = White:6, ethnicity = White:5
(map1 <- setNames(df11$ethniccode, df11$ethnic))
dfdig[c("ethnicityomb")] <- lapply(dfdig[c("ethnicityomb")],function(x) map1[as.character(x)])
fn<-file.path(datafile_year)
if (file.exists(fn)) file.remove(fn)
}
IAT_2016_format_exception<- function(year){
  df <- read.csv(paste0("Race IAT.public.",year,".csv"))
  df2 <- df[grepl(pattern="[[:digit:]]", df$countrycit)|grepl(pattern="[[:digit:]]", df$countryres), ]
  dfdig <- df2[!grepl(pattern="-9", df2$countrycit), ]
  ###Start Matching Values from Codebook
  df$countrycit[df$countrycit == 1] <-  "US"
  df$countrycit[df$countrycit == 2] <-  "AF"
  df$countrycit[df$countrycit == 3] <-  "AL"
  df$countrycit[df$countrycit == 4] <-  "DZ"
  df$countrycit[df$countrycit == 5] <-  "AS"
  df$countrycit[df$countrycit == 6] <-  "AD"
  df$countrycit[df$countrycit == 7] <-  "AO"
  df$countrycit[df$countrycit == 8] <-  "AI"
  df$countrycit[df$countrycit == 9] <-  "NULL"
  df$countrycit[df$countrycit == 10] <-  "AG"
  df$countrycit[df$countrycit == 11] <-  "AR"
  df$countrycit[df$countrycit == 12] <-  "AM"
  df$countrycit[df$countrycit == 13] <-  "AW"
  df$countrycit[df$countrycit == 14] <-  "AU"
  df$countrycit[df$countrycit == 15] <-  "AT"
  df$countrycit[df$countrycit == 16] <-  "AZ"
  df$countrycit[df$countrycit == 17] <-  "BS"
  df$countrycit[df$countrycit == 18] <-  "BH"
  df$countrycit[df$countrycit == 19] <-  "BD"
  df$countrycit[df$countrycit == 20] <-  "BB"
  df$countrycit[df$countrycit == 21] <-  "BY"
  df$countrycit[df$countrycit == 22] <-  "BE"
  df$countrycit[df$countrycit == 23] <-  "BZ"
  df$countrycit[df$countrycit == 24] <-  "BJ"
  df$countrycit[df$countrycit == 25] <-  "BM"
  df$countrycit[df$countrycit == 26] <-  "BT"
  df$countrycit[df$countrycit == 27] <-  "BO"
  df$countrycit[df$countrycit == 28] <-  "BA"
  df$countrycit[df$countrycit == 29] <-  "BW"
  df$countrycit[df$countrycit == 30] <-  "NULL"
  df$countrycit[df$countrycit == 31] <-  "BR"
  df$countrycit[df$countrycit == 32] <-  "NULL"
  df$countrycit[df$countrycit == 33] <-  "BN"
  df$countrycit[df$countrycit == 34] <-  "BG"
  df$countrycit[df$countrycit == 35] <-  "BF"
  df$countrycit[df$countrycit == 36] <-  "BI"
  df$countrycit[df$countrycit == 37] <-  "KH"
  df$countrycit[df$countrycit == 38] <-  "CM"
  df$countrycit[df$countrycit == 39] <-  "CA"
  df$countrycit[df$countrycit == 40] <-  "CV"
  df$countrycit[df$countrycit == 41] <-  "KY"
  df$countrycit[df$countrycit == 42] <-  "CF"
  df$countrycit[df$countrycit == 43] <-  "TD"
  df$countrycit[df$countrycit == 44] <-  "CL"
  df$countrycit[df$countrycit == 45] <-  "CN"
  df$countrycit[df$countrycit == 46] <-  "NULL"
  df$countrycit[df$countrycit == 47] <-  "NULL"
  df$countrycit[df$countrycit == 48] <-  "CO"
  df$countrycit[df$countrycit == 49] <-  "KM"
  df$countrycit[df$countrycit == 50] <-  "CG"
  df$countrycit[df$countrycit == 51] <-  "NULL"
  df$countrycit[df$countrycit == 52] <-  "CK"
  df$countrycit[df$countrycit == 53] <-  "CR"
  df$countrycit[df$countrycit == 54] <-  "NULL"
  df$countrycit[df$countrycit == 55] <-  "NULL"
  df$countrycit[df$countrycit == 56] <-  "CU"
  df$countrycit[df$countrycit == 57] <-  "CY"
  df$countrycit[df$countrycit == 58] <-  "CZ"
  df$countrycit[df$countrycit == 59] <-  "DK"
  df$countrycit[df$countrycit == 60] <-  "DJ"
  df$countrycit[df$countrycit == 61] <-  "DM"
  df$countrycit[df$countrycit == 62] <-  "DO"
  df$countrycit[df$countrycit == 63] <-  "NULL"
  df$countrycit[df$countrycit == 64] <-  "EC"
  df$countrycit[df$countrycit == 65] <-  "EG"
  df$countrycit[df$countrycit == 66] <-  "SV"
  df$countrycit[df$countrycit == 67] <-  "GQ"
  df$countrycit[df$countrycit == 68] <-  "ER"
  df$countrycit[df$countrycit == 69] <-  "EE"
  df$countrycit[df$countrycit == 70] <-  "ET"
  df$countrycit[df$countrycit == 71] <-  "NULL"
  df$countrycit[df$countrycit == 72] <-  "NULL"
  df$countrycit[df$countrycit == 73] <-  "NULL"
  df$countrycit[df$countrycit == 74] <-  "FI"
  df$countrycit[df$countrycit == 75] <-  "FR"
  df$countrycit[df$countrycit == 76] <-  "GF"
  df$countrycit[df$countrycit == 77] <-  "PF"
  df$countrycit[df$countrycit == 78] <-  "NULL"
  df$countrycit[df$countrycit == 79] <-  "GA"
  df$countrycit[df$countrycit == 80] <-  "GM"
  df$countrycit[df$countrycit == 81] <-  "GE"
  df$countrycit[df$countrycit == 82] <-  "DE"
  df$countrycit[df$countrycit == 83] <-  "GH"
  df$countrycit[df$countrycit == 84] <-  "GI"
  df$countrycit[df$countrycit == 85] <-  "GR"
  df$countrycit[df$countrycit == 86] <-  "GL"
  df$countrycit[df$countrycit == 87] <-  "GD"
  df$countrycit[df$countrycit == 88] <-  "GP"
  df$countrycit[df$countrycit == 89] <-  "GU"
  df$countrycit[df$countrycit == 90] <-  "GT"
  df$countrycit[df$countrycit == 91] <-  "GN"
  df$countrycit[df$countrycit == 92] <-  "GW"
  df$countrycit[df$countrycit == 93] <-  "GY"
  df$countrycit[df$countrycit == 94] <-  "HT"
  df$countrycit[df$countrycit == 95] <-  "NULL"
  df$countrycit[df$countrycit == 96] <-  "HN"
  df$countrycit[df$countrycit == 97] <-  "NULL"
  df$countrycit[df$countrycit == 98] <-  "HU"
  df$countrycit[df$countrycit == 99] <-  "IS"
  df$countrycit[df$countrycit == 100] <-  "IN"
  df$countrycit[df$countrycit == 101] <-  "ID"
  df$countrycit[df$countrycit == 102] <-  "IR"
  df$countrycit[df$countrycit == 103] <-  "IQ"
  df$countrycit[df$countrycit == 104] <-  "IE"
  df$countrycit[df$countrycit == 105] <-  "IL"
  df$countrycit[df$countrycit == 106] <-  "IT"
  df$countrycit[df$countrycit == 107] <-  "JM"
  df$countrycit[df$countrycit == 108] <-  "JP"
  df$countrycit[df$countrycit == 109] <-  "JO"
  df$countrycit[df$countrycit == 110] <-  "KZ"
  df$countrycit[df$countrycit == 111] <-  "KE"
  df$countrycit[df$countrycit == 112] <-  "KI"
  df$countrycit[df$countrycit == 113] <-  "KR"
  df$countrycit[df$countrycit == 114] <-  "NULL"
  df$countrycit[df$countrycit == 115] <-  "KW"
  df$countrycit[df$countrycit == 116] <-  "KG"
  df$countrycit[df$countrycit == 117] <-  "LA"
  df$countrycit[df$countrycit == 118] <-  "LV"
  df$countrycit[df$countrycit == 119] <-  "LB"
  df$countrycit[df$countrycit == 120] <-  "LS"
  df$countrycit[df$countrycit == 121] <-  "LR"
  df$countrycit[df$countrycit == 122] <-  "LY"
  df$countrycit[df$countrycit == 123] <-  "LI"
  df$countrycit[df$countrycit == 124] <-  "LT"
  df$countrycit[df$countrycit == 125] <-  "LU"
  df$countrycit[df$countrycit == 126] <-  "NULL"
  df$countrycit[df$countrycit == 127] <-  "NULL"
  df$countrycit[df$countrycit == 128] <-  "MG"
  df$countrycit[df$countrycit == 129] <-  "MW"
  df$countrycit[df$countrycit == 130] <-  "MY"
  df$countrycit[df$countrycit == 131] <-  "MV"
  df$countrycit[df$countrycit == 132] <-  "ML"
  df$countrycit[df$countrycit == 133] <-  "MT"
  df$countrycit[df$countrycit == 134] <-  "MH"
  df$countrycit[df$countrycit == 135] <-  "MQ"
  df$countrycit[df$countrycit == 136] <-  "MR"
  df$countrycit[df$countrycit == 137] <-  "MU"
  df$countrycit[df$countrycit == 138] <-  "NULL"
  df$countrycit[df$countrycit == 139] <-  "MX"
  df$countrycit[df$countrycit == 140] <-  "NULL"
  df$countrycit[df$countrycit == 141] <-  "MD"
  df$countrycit[df$countrycit == 142] <-  "MC"
  df$countrycit[df$countrycit == 143] <-  "MN"
  df$countrycit[df$countrycit == 144] <-  "ME"
  df$countrycit[df$countrycit == 145] <-  "NULL"
  df$countrycit[df$countrycit == 146] <-  "MA"
  df$countrycit[df$countrycit == 147] <-  "MZ"
  df$countrycit[df$countrycit == 148] <-  "MM"
  df$countrycit[df$countrycit == 149] <-  "NA"
  df$countrycit[df$countrycit == 150] <-  "NULL"
  df$countrycit[df$countrycit == 151] <-  "NP"
  df$countrycit[df$countrycit == 152] <-  "NULL"
  df$countrycit[df$countrycit == 154] <-  "NC"
  df$countrycit[df$countrycit == 155] <-  "NZ"
  df$countrycit[df$countrycit == 156] <-  "NI"
  df$countrycit[df$countrycit == 157] <-  "NE"
  df$countrycit[df$countrycit == 158] <-  "NG"
  df$countrycit[df$countrycit == 159] <-  "NULL"
  df$countrycit[df$countrycit == 160] <-  "NULL"
  df$countrycit[df$countrycit == 161] <-  "MP"
  df$countrycit[df$countrycit == 162] <-  "NO"
  df$countrycit[df$countrycit == 163] <-  "OM"
  df$countrycit[df$countrycit == 164] <-  "PK"
  df$countrycit[df$countrycit == 165] <-  "PW"
  df$countrycit[df$countrycit == 240] <-  "PS"
  df$countrycit[df$countrycit == 166] <-  "PA"
  df$countrycit[df$countrycit == 167] <-  "PG"
  df$countrycit[df$countrycit == 168] <-  "PY"
  df$countrycit[df$countrycit == 169] <-  "PE"
  df$countrycit[df$countrycit == 170] <-  "PH"
  df$countrycit[df$countrycit == 171] <-  "NULL"
  df$countrycit[df$countrycit == 172] <-  "PL"
  df$countrycit[df$countrycit == 173] <-  "PT"
  df$countrycit[df$countrycit == 174] <-  "PR"
  df$countrycit[df$countrycit == 175] <-  "QA"
  df$countrycit[df$countrycit == 176] <-  "NULL"
  df$countrycit[df$countrycit == 177] <-  "RO"
  df$countrycit[df$countrycit == 178] <-  "RU"
  df$countrycit[df$countrycit == 179] <-  "RW"
  df$countrycit[df$countrycit == 180] <-  "NULL"
  df$countrycit[df$countrycit == 181] <-  "NULL"
  df$countrycit[df$countrycit == 182] <-  "LC"
  df$countrycit[df$countrycit == 183] <-  "NULL"
  df$countrycit[df$countrycit == 184] <-  "VC"
  df$countrycit[df$countrycit == 185] <-  "WS"
  df$countrycit[df$countrycit == 186] <-  "SM"
  df$countrycit[df$countrycit == 187] <-  "NULL"
  df$countrycit[df$countrycit == 188] <-  "SA"
  df$countrycit[df$countrycit == 189] <-  "SN"
  df$countrycit[df$countrycit == 241] <-  "RS"
  df$countrycit[df$countrycit == 190] <-  "SC"
  df$countrycit[df$countrycit == 191] <-  "SL"
  df$countrycit[df$countrycit == 192] <-  "SG"
  df$countrycit[df$countrycit == 193] <-  "SK"
  df$countrycit[df$countrycit == 194] <-  "SI"
  df$countrycit[df$countrycit == 195] <-  "SB"
  df$countrycit[df$countrycit == 196] <-  "SO"
  df$countrycit[df$countrycit == 197] <-  "ZA"
  df$countrycit[df$countrycit == 198] <-  "NULL"
  df$countrycit[df$countrycit == 199] <-  "SS"
  df$countrycit[df$countrycit == 200] <-  "ES"
  df$countrycit[df$countrycit == 201] <-  "LK"
  df$countrycit[df$countrycit == 202] <-  "SD"
  df$countrycit[df$countrycit == 203] <-  "SR"
  df$countrycit[df$countrycit == 204] <-  "NULL"
  df$countrycit[df$countrycit == 205] <-  "SZ"
  df$countrycit[df$countrycit == 206] <-  "SE"
  df$countrycit[df$countrycit == 207] <-  "CH"
  df$countrycit[df$countrycit == 208] <-  "SY"
  df$countrycit[df$countrycit == 209] <-  "TW"
  df$countrycit[df$countrycit == 210] <-  "TJ"
  df$countrycit[df$countrycit == 211] <-  "TZ"
  df$countrycit[df$countrycit == 212] <-  "TH"
  df$countrycit[df$countrycit == 153] <-  "NULL"
  df$countrycit[df$countrycit == 213] <-  "TG"
  df$countrycit[df$countrycit == 214] <-  "NULL"
  df$countrycit[df$countrycit == 215] <-  "NULL"
  df$countrycit[df$countrycit == 216] <-  "TT"
  df$countrycit[df$countrycit == 217] <-  "TN"
  df$countrycit[df$countrycit == 218] <-  "TR"
  df$countrycit[df$countrycit == 219] <-  "TM"
  df$countrycit[df$countrycit == 220] <-  "TC"
  df$countrycit[df$countrycit == 221] <-  "NULL"
  df$countrycit[df$countrycit == 222] <-  "UG"
  df$countrycit[df$countrycit == 223] <-  "UA"
  df$countrycit[df$countrycit == 224] <-  "AE"
  df$countrycit[df$countrycit == 225] <-  "GB"
  df$countrycit[df$countrycit == 226] <-  "NULL"
  df$countrycit[df$countrycit == 227] <-  "UY"
  df$countrycit[df$countrycit == 228] <-  "UZ"
  df$countrycit[df$countrycit == 229] <-  "NULL"
  df$countrycit[df$countrycit == 230] <-  "NULL"
  df$countrycit[df$countrycit == 231] <-  "VE"
  df$countrycit[df$countrycit == 232] <-  "VN"
  df$countrycit[df$countrycit == 233] <-  "NULL"
  df$countrycit[df$countrycit == 234] <-  "NULL"
  df$countrycit[df$countrycit == 235] <-  "NULL"
  df$countrycit[df$countrycit == 236] <-  "YE"
  df$countrycit[df$countrycit == 238] <-  "ZM"
  df$countrycit[df$countrycit == 239] <-  "ZW"
  
  
  df$countryres[df$countryres == 1] <-  "US"
  df$countryres[df$countryres == 2] <-  "AF"
  df$countryres[df$countryres == 3] <-  "AL"
  df$countryres[df$countryres == 4] <-  "DZ"
  df$countryres[df$countryres == 5] <-  "AS"
  df$countryres[df$countryres == 6] <-  "AD"
  df$countryres[df$countryres == 7] <-  "AO"
  df$countryres[df$countryres == 8] <-  "AI"
  df$countryres[df$countryres == 9] <-  "NULL"
  df$countryres[df$countryres == 10] <-  "AG"
  df$countryres[df$countryres == 11] <-  "AR"
  df$countryres[df$countryres == 12] <-  "AM"
  df$countryres[df$countryres == 13] <-  "AW"
  df$countryres[df$countryres == 14] <-  "AU"
  df$countryres[df$countryres == 15] <-  "AT"
  df$countryres[df$countryres == 16] <-  "AZ"
  df$countryres[df$countryres == 17] <-  "BS"
  df$countryres[df$countryres == 18] <-  "BH"
  df$countryres[df$countryres == 19] <-  "BD"
  df$countryres[df$countryres == 20] <-  "BB"
  df$countryres[df$countryres == 21] <-  "BY"
  df$countryres[df$countryres == 22] <-  "BE"
  df$countryres[df$countryres == 23] <-  "BZ"
  df$countryres[df$countryres == 24] <-  "BJ"
  df$countryres[df$countryres == 25] <-  "BM"
  df$countryres[df$countryres == 26] <-  "BT"
  df$countryres[df$countryres == 27] <-  "BO"
  df$countryres[df$countryres == 28] <-  "BA"
  df$countryres[df$countryres == 29] <-  "BW"
  df$countryres[df$countryres == 30] <-  "NULL"
  df$countryres[df$countryres == 31] <-  "BR"
  df$countryres[df$countryres == 32] <-  "NULL"
  df$countryres[df$countryres == 33] <-  "BN"
  df$countryres[df$countryres == 34] <-  "BG"
  df$countryres[df$countryres == 35] <-  "BF"
  df$countryres[df$countryres == 36] <-  "BI"
  df$countryres[df$countryres == 37] <-  "KH"
  df$countryres[df$countryres == 38] <-  "CM"
  df$countryres[df$countryres == 39] <-  "CA"
  df$countryres[df$countryres == 40] <-  "CV"
  df$countryres[df$countryres == 41] <-  "KY"
  df$countryres[df$countryres == 42] <-  "CF"
  df$countryres[df$countryres == 43] <-  "TD"
  df$countryres[df$countryres == 44] <-  "CL"
  df$countryres[df$countryres == 45] <-  "CN"
  df$countryres[df$countryres == 46] <-  "NULL"
  df$countryres[df$countryres == 47] <-  "NULL"
  df$countryres[df$countryres == 48] <-  "CO"
  df$countryres[df$countryres == 49] <-  "KM"
  df$countryres[df$countryres == 50] <-  "CG"
  df$countryres[df$countryres == 51] <-  "NULL"
  df$countryres[df$countryres == 52] <-  "CK"
  df$countryres[df$countryres == 53] <-  "CR"
  df$countryres[df$countryres == 54] <-  "NULL"
  df$countryres[df$countryres == 55] <-  "NULL"
  df$countryres[df$countryres == 56] <-  "CU"
  df$countryres[df$countryres == 57] <-  "CY"
  df$countryres[df$countryres == 58] <-  "CZ"
  df$countryres[df$countryres == 59] <-  "DK"
  df$countryres[df$countryres == 60] <-  "DJ"
  df$countryres[df$countryres == 61] <-  "DM"
  df$countryres[df$countryres == 62] <-  "DO"
  df$countryres[df$countryres == 63] <-  "NULL"
  df$countryres[df$countryres == 64] <-  "EC"
  df$countryres[df$countryres == 65] <-  "EG"
  df$countryres[df$countryres == 66] <-  "SV"
  df$countryres[df$countryres == 67] <-  "GQ"
  df$countryres[df$countryres == 68] <-  "ER"
  df$countryres[df$countryres == 69] <-  "EE"
  df$countryres[df$countryres == 70] <-  "ET"
  df$countryres[df$countryres == 71] <-  "NULL"
  df$countryres[df$countryres == 72] <-  "NULL"
  df$countryres[df$countryres == 73] <-  "NULL"
  df$countryres[df$countryres == 74] <-  "FI"
  df$countryres[df$countryres == 75] <-  "FR"
  df$countryres[df$countryres == 76] <-  "GF"
  df$countryres[df$countryres == 77] <-  "PF"
  df$countryres[df$countryres == 78] <-  "NULL"
  df$countryres[df$countryres == 79] <-  "GA"
  df$countryres[df$countryres == 80] <-  "GM"
  df$countryres[df$countryres == 81] <-  "GE"
  df$countryres[df$countryres == 82] <-  "DE"
  df$countryres[df$countryres == 83] <-  "GH"
  df$countryres[df$countryres == 84] <-  "GI"
  df$countryres[df$countryres == 85] <-  "GR"
  df$countryres[df$countryres == 86] <-  "GL"
  df$countryres[df$countryres == 87] <-  "GD"
  df$countryres[df$countryres == 88] <-  "GP"
  df$countryres[df$countryres == 89] <-  "GU"
  df$countryres[df$countryres == 90] <-  "GT"
  df$countryres[df$countryres == 91] <-  "GN"
  df$countryres[df$countryres == 92] <-  "GW"
  df$countryres[df$countryres == 93] <-  "GY"
  df$countryres[df$countryres == 94] <-  "HT"
  df$countryres[df$countryres == 95] <-  "NULL"
  df$countryres[df$countryres == 96] <-  "HN"
  df$countryres[df$countryres == 97] <-  "NULL"
  df$countryres[df$countryres == 98] <-  "HU"
  df$countryres[df$countryres == 99] <-  "IS"
  df$countryres[df$countryres == 100] <-  "IN"
  df$countryres[df$countryres == 101] <-  "ID"
  df$countryres[df$countryres == 102] <-  "IR"
  df$countryres[df$countryres == 103] <-  "IQ"
  df$countryres[df$countryres == 104] <-  "IE"
  df$countryres[df$countryres == 105] <-  "IL"
  df$countryres[df$countryres == 106] <-  "IT"
  df$countryres[df$countryres == 107] <-  "JM"
  df$countryres[df$countryres == 108] <-  "JP"
  df$countryres[df$countryres == 109] <-  "JO"
  df$countryres[df$countryres == 110] <-  "KZ"
  df$countryres[df$countryres == 111] <-  "KE"
  df$countryres[df$countryres == 112] <-  "KI"
  df$countryres[df$countryres == 113] <-  "KR"
  df$countryres[df$countryres == 114] <-  "NULL"
  df$countryres[df$countryres == 115] <-  "KW"
  df$countryres[df$countryres == 116] <-  "KG"
  df$countryres[df$countryres == 117] <-  "LA"
  df$countryres[df$countryres == 118] <-  "LV"
  df$countryres[df$countryres == 119] <-  "LB"
  df$countryres[df$countryres == 120] <-  "LS"
  df$countryres[df$countryres == 121] <-  "LR"
  df$countryres[df$countryres == 122] <-  "LY"
  df$countryres[df$countryres == 123] <-  "LI"
  df$countryres[df$countryres == 124] <-  "LT"
  df$countryres[df$countryres == 125] <-  "LU"
  df$countryres[df$countryres == 126] <-  "NULL"
  df$countryres[df$countryres == 127] <-  "NULL"
  df$countryres[df$countryres == 128] <-  "MG"
  df$countryres[df$countryres == 129] <-  "MW"
  df$countryres[df$countryres == 130] <-  "MY"
  df$countryres[df$countryres == 131] <-  "MV"
  df$countryres[df$countryres == 132] <-  "ML"
  df$countryres[df$countryres == 133] <-  "MT"
  df$countryres[df$countryres == 134] <-  "MH"
  df$countryres[df$countryres == 135] <-  "MQ"
  df$countryres[df$countryres == 136] <-  "MR"
  df$countryres[df$countryres == 137] <-  "MU"
  df$countryres[df$countryres == 138] <-  "NULL"
  df$countryres[df$countryres == 139] <-  "MX"
  df$countryres[df$countryres == 140] <-  "NULL"
  df$countryres[df$countryres == 141] <-  "MD"
  df$countryres[df$countryres == 142] <-  "MC"
  df$countryres[df$countryres == 143] <-  "MN"
  df$countryres[df$countryres == 144] <-  "ME"
  df$countryres[df$countryres == 145] <-  "NULL"
  df$countryres[df$countryres == 146] <-  "MA"
  df$countryres[df$countryres == 147] <-  "MZ"
  df$countryres[df$countryres == 148] <-  "MM"
  df$countryres[df$countryres == 149] <-  "NA"
  df$countryres[df$countryres == 150] <-  "NULL"
  df$countryres[df$countryres == 151] <-  "NP"
  df$countryres[df$countryres == 152] <-  "NULL"
  df$countryres[df$countryres == 154] <-  "NC"
  df$countryres[df$countryres == 155] <-  "NZ"
  df$countryres[df$countryres == 156] <-  "NI"
  df$countryres[df$countryres == 157] <-  "NE"
  df$countryres[df$countryres == 158] <-  "NG"
  df$countryres[df$countryres == 159] <-  "NULL"
  df$countryres[df$countryres == 160] <-  "NULL"
  df$countryres[df$countryres == 161] <-  "MP"
  df$countryres[df$countryres == 162] <-  "NO"
  df$countryres[df$countryres == 163] <-  "OM"
  df$countryres[df$countryres == 164] <-  "PK"
  df$countryres[df$countryres == 165] <-  "PW"
  df$countryres[df$countryres == 240] <-  "PS"
  df$countryres[df$countryres == 166] <-  "PA"
  df$countryres[df$countryres == 167] <-  "PG"
  df$countryres[df$countryres == 168] <-  "PY"
  df$countryres[df$countryres == 169] <-  "PE"
  df$countryres[df$countryres == 170] <-  "PH"
  df$countryres[df$countryres == 171] <-  "NULL"
  df$countryres[df$countryres == 172] <-  "PL"
  df$countryres[df$countryres == 173] <-  "PT"
  df$countryres[df$countryres == 174] <-  "PR"
  df$countryres[df$countryres == 175] <-  "QA"
  df$countryres[df$countryres == 176] <-  "NULL"
  df$countryres[df$countryres == 177] <-  "RO"
  df$countryres[df$countryres == 178] <-  "RU"
  df$countryres[df$countryres == 179] <-  "RW"
  df$countryres[df$countryres == 180] <-  "NULL"
  df$countryres[df$countryres == 181] <-  "NULL"
  df$countryres[df$countryres == 182] <-  "LC"
  df$countryres[df$countryres == 183] <-  "NULL"
  df$countryres[df$countryres == 184] <-  "VC"
  df$countryres[df$countryres == 185] <-  "WS"
  df$countryres[df$countryres == 186] <-  "SM"
  df$countryres[df$countryres == 187] <-  "NULL"
  df$countryres[df$countryres == 188] <-  "SA"
  df$countryres[df$countryres == 189] <-  "SN"
  df$countryres[df$countryres == 241] <-  "RS"
  df$countryres[df$countryres == 190] <-  "SC"
  df$countryres[df$countryres == 191] <-  "SL"
  df$countryres[df$countryres == 192] <-  "SG"
  df$countryres[df$countryres == 193] <-  "SK"
  df$countryres[df$countryres == 194] <-  "SI"
  df$countryres[df$countryres == 195] <-  "SB"
  df$countryres[df$countryres == 196] <-  "SO"
  df$countryres[df$countryres == 197] <-  "ZA"
  df$countryres[df$countryres == 198] <-  "NULL"
  df$countryres[df$countryres == 199] <-  "SS"
  df$countryres[df$countryres == 200] <-  "ES"
  df$countryres[df$countryres == 201] <-  "LK"
  df$countryres[df$countryres == 202] <-  "SD"
  df$countryres[df$countryres == 203] <-  "SR"
  df$countryres[df$countryres == 204] <-  "NULL"
  df$countryres[df$countryres == 205] <-  "SZ"
  df$countryres[df$countryres == 206] <-  "SE"
  df$countryres[df$countryres == 207] <-  "CH"
  df$countryres[df$countryres == 208] <-  "SY"
  df$countryres[df$countryres == 209] <-  "TW"
  df$countryres[df$countryres == 210] <-  "TJ"
  df$countryres[df$countryres == 211] <-  "TZ"
  df$countryres[df$countryres == 212] <-  "TH"
  df$countryres[df$countryres == 153] <-  "NULL"
  df$countryres[df$countryres == 213] <-  "TG"
  df$countryres[df$countryres == 214] <-  "NULL"
  df$countryres[df$countryres == 215] <-  "NULL"
  df$countryres[df$countryres == 216] <-  "TT"
  df$countryres[df$countryres == 217] <-  "TN"
  df$countryres[df$countryres == 218] <-  "TR"
  df$countryres[df$countryres == 219] <-  "TM"
  df$countryres[df$countryres == 220] <-  "TC"
  df$countryres[df$countryres == 221] <-  "NULL"
  df$countryres[df$countryres == 222] <-  "UG"
  df$countryres[df$countryres == 223] <-  "UA"
  df$countryres[df$countryres == 224] <-  "AE"
  df$countryres[df$countryres == 225] <-  "GB"
  df$countryres[df$countryres == 226] <-  "NULL"
  df$countryres[df$countryres == 227] <-  "UY"
  df$countryres[df$countryres == 228] <-  "UZ"
  df$countryres[df$countryres == 229] <-  "NULL"
  df$countryres[df$countryres == 230] <-  "NULL"
  df$countryres[df$countryres == 231] <-  "VE"
  df$countryres[df$countryres == 232] <-  "VN"
  df$countryres[df$countryres == 233] <-  "NULL"
  df$countryres[df$countryres == 234] <-  "NULL"
  df$countryres[df$countryres == 235] <-  "NULL"
  df$countryres[df$countryres == 236] <-  "YE"
  df$countryres[df$countryres == 238] <-  "ZM"
  df$countryres[df$countryres == 239] <-  "ZW"
  ###End Matching Values from Codebook
  dfalp <- df[grepl(pattern="[[:alpha:]]", df$countrycit) & !grepl(pattern="[[:digit:]]", df$countryres), ]
  write.csv(dfdig, file.path(paste0("RaceIAT_public_",year,"_digit.csv")), row.names=FALSE, quote=FALSE)
  write.csv(dfalp, file.path(paste0("RaceIAT_public_",year,"_alpha.csv")), row.names=FALSE, quote=FALSE)
  #Deleting the old file to replace with the processed file
  fn <- file.path(paste0("Race IAT.public.",year,".csv"))
  if (file.exists(fn)) file.remove(fn)
  
  ###### Merging or mapping the files ######
  ## Processing the new format files
  datafile_year=paste0("RaceIAT_public_",year,"_digit.csv")
  df1 <- read.delim(file.path(Sys.getenv('my_dir'),'2021/05/impicit_racial_bias/original_european_map_of_implicit_racial_bias/data/Mapper.txt'))
  df11 <- read.delim(file.path(Sys.getenv('my_dir'),'2021/05/impicit_racial_bias/original_european_map_of_implicit_racial_bias/data/Ethnic.txt'))
  dfdig <- read.csv(datafile_year, header=TRUE)
  (map <- setNames(df1$countrycitcode, df1$countrycit))
  if (file.exists(fn)) file.remove(datafile_year)
  dfdig[c("countrycit", "countryres")] <- lapply(dfdig[c("countrycit", "countryres")],function(x) map[as.character(x)])
  ##race = White:6, ethnicity = White:5
  (map1 <- setNames(df11$ethniccode, df11$ethnic))
  dfdig[c("ethnicityomb")] <- lapply(dfdig[c("ethnicityomb")],function(x) map1[as.character(x)])
  fn<-file.path(datafile_year)
  if (file.exists(fn)) file.remove(fn)
}

IAT_2015_format_exception(2015)
IAT_2016_format_exception(2016)

IAT_modern_format_2017_and_later<- function(year){
  df <- read.csv(paste0("Race IAT.public.",year,".csv"))
  df2 <- df[grepl(pattern="[[:digit:]]", df$countrycit_num)|grepl(pattern="[[:digit:]]", df$countryres_num), ]
  dfdig <- df2[!grepl(pattern="-9", df2$countrycit_num), ]
  ###Start Matching Values from Codebook
  df$countrycit_num[df$countrycit_num == 1] <-  "US"
  df$countrycit_num[df$countrycit_num == 2] <-  "AF"
  df$countrycit_num[df$countrycit_num == 3] <-  "AL"
  df$countrycit_num[df$countrycit_num == 4] <-  "DZ"
  df$countrycit_num[df$countrycit_num == 5] <-  "AS"
  df$countrycit_num[df$countrycit_num == 6] <-  "AD"
  df$countrycit_num[df$countrycit_num == 7] <-  "AO"
  df$countrycit_num[df$countrycit_num == 8] <-  "AI"
  df$countrycit_num[df$countrycit_num == 9] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 10] <-  "AG"
  df$countrycit_num[df$countrycit_num == 11] <-  "AR"
  df$countrycit_num[df$countrycit_num == 12] <-  "AM"
  df$countrycit_num[df$countrycit_num == 13] <-  "AW"
  df$countrycit_num[df$countrycit_num == 14] <-  "AU"
  df$countrycit_num[df$countrycit_num == 15] <-  "AT"
  df$countrycit_num[df$countrycit_num == 16] <-  "AZ"
  df$countrycit_num[df$countrycit_num == 17] <-  "BS"
  df$countrycit_num[df$countrycit_num == 18] <-  "BH"
  df$countrycit_num[df$countrycit_num == 19] <-  "BD"
  df$countrycit_num[df$countrycit_num == 20] <-  "BB"
  df$countrycit_num[df$countrycit_num == 21] <-  "BY"
  df$countrycit_num[df$countrycit_num == 22] <-  "BE"
  df$countrycit_num[df$countrycit_num == 23] <-  "BZ"
  df$countrycit_num[df$countrycit_num == 24] <-  "BJ"
  df$countrycit_num[df$countrycit_num == 25] <-  "BM"
  df$countrycit_num[df$countrycit_num == 26] <-  "BT"
  df$countrycit_num[df$countrycit_num == 27] <-  "BO"
  df$countrycit_num[df$countrycit_num == 28] <-  "BA"
  df$countrycit_num[df$countrycit_num == 29] <-  "BW"
  df$countrycit_num[df$countrycit_num == 30] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 31] <-  "BR"
  df$countrycit_num[df$countrycit_num == 32] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 33] <-  "BN"
  df$countrycit_num[df$countrycit_num == 34] <-  "BG"
  df$countrycit_num[df$countrycit_num == 35] <-  "BF"
  df$countrycit_num[df$countrycit_num == 36] <-  "BI"
  df$countrycit_num[df$countrycit_num == 37] <-  "KH"
  df$countrycit_num[df$countrycit_num == 38] <-  "CM"
  df$countrycit_num[df$countrycit_num == 39] <-  "CA"
  df$countrycit_num[df$countrycit_num == 40] <-  "CV"
  df$countrycit_num[df$countrycit_num == 41] <-  "KY"
  df$countrycit_num[df$countrycit_num == 42] <-  "CF"
  df$countrycit_num[df$countrycit_num == 43] <-  "TD"
  df$countrycit_num[df$countrycit_num == 44] <-  "CL"
  df$countrycit_num[df$countrycit_num == 45] <-  "CN"
  df$countrycit_num[df$countrycit_num == 46] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 47] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 48] <-  "CO"
  df$countrycit_num[df$countrycit_num == 49] <-  "KM"
  df$countrycit_num[df$countrycit_num == 50] <-  "CG"
  df$countrycit_num[df$countrycit_num == 51] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 52] <-  "CK"
  df$countrycit_num[df$countrycit_num == 53] <-  "CR"
  df$countrycit_num[df$countrycit_num == 54] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 55] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 56] <-  "CU"
  df$countrycit_num[df$countrycit_num == 57] <-  "CY"
  df$countrycit_num[df$countrycit_num == 58] <-  "CZ"
  df$countrycit_num[df$countrycit_num == 59] <-  "DK"
  df$countrycit_num[df$countrycit_num == 60] <-  "DJ"
  df$countrycit_num[df$countrycit_num == 61] <-  "DM"
  df$countrycit_num[df$countrycit_num == 62] <-  "DO"
  df$countrycit_num[df$countrycit_num == 63] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 64] <-  "EC"
  df$countrycit_num[df$countrycit_num == 65] <-  "EG"
  df$countrycit_num[df$countrycit_num == 66] <-  "SV"
  df$countrycit_num[df$countrycit_num == 67] <-  "GQ"
  df$countrycit_num[df$countrycit_num == 68] <-  "ER"
  df$countrycit_num[df$countrycit_num == 69] <-  "EE"
  df$countrycit_num[df$countrycit_num == 70] <-  "ET"
  df$countrycit_num[df$countrycit_num == 71] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 72] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 73] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 74] <-  "FI"
  df$countrycit_num[df$countrycit_num == 75] <-  "FR"
  df$countrycit_num[df$countrycit_num == 76] <-  "GF"
  df$countrycit_num[df$countrycit_num == 77] <-  "PF"
  df$countrycit_num[df$countrycit_num == 78] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 79] <-  "GA"
  df$countrycit_num[df$countrycit_num == 80] <-  "GM"
  df$countrycit_num[df$countrycit_num == 81] <-  "GE"
  df$countrycit_num[df$countrycit_num == 82] <-  "DE"
  df$countrycit_num[df$countrycit_num == 83] <-  "GH"
  df$countrycit_num[df$countrycit_num == 84] <-  "GI"
  df$countrycit_num[df$countrycit_num == 85] <-  "GR"
  df$countrycit_num[df$countrycit_num == 86] <-  "GL"
  df$countrycit_num[df$countrycit_num == 87] <-  "GD"
  df$countrycit_num[df$countrycit_num == 88] <-  "GP"
  df$countrycit_num[df$countrycit_num == 89] <-  "GU"
  df$countrycit_num[df$countrycit_num == 90] <-  "GT"
  df$countrycit_num[df$countrycit_num == 91] <-  "GN"
  df$countrycit_num[df$countrycit_num == 92] <-  "GW"
  df$countrycit_num[df$countrycit_num == 93] <-  "GY"
  df$countrycit_num[df$countrycit_num == 94] <-  "HT"
  df$countrycit_num[df$countrycit_num == 95] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 96] <-  "HN"
  df$countrycit_num[df$countrycit_num == 97] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 98] <-  "HU"
  df$countrycit_num[df$countrycit_num == 99] <-  "IS"
  df$countrycit_num[df$countrycit_num == 100] <-  "IN"
  df$countrycit_num[df$countrycit_num == 101] <-  "ID"
  df$countrycit_num[df$countrycit_num == 102] <-  "IR"
  df$countrycit_num[df$countrycit_num == 103] <-  "IQ"
  df$countrycit_num[df$countrycit_num == 104] <-  "IE"
  df$countrycit_num[df$countrycit_num == 105] <-  "IL"
  df$countrycit_num[df$countrycit_num == 106] <-  "IT"
  df$countrycit_num[df$countrycit_num == 107] <-  "JM"
  df$countrycit_num[df$countrycit_num == 108] <-  "JP"
  df$countrycit_num[df$countrycit_num == 109] <-  "JO"
  df$countrycit_num[df$countrycit_num == 110] <-  "KZ"
  df$countrycit_num[df$countrycit_num == 111] <-  "KE"
  df$countrycit_num[df$countrycit_num == 112] <-  "KI"
  df$countrycit_num[df$countrycit_num == 113] <-  "KR"
  df$countrycit_num[df$countrycit_num == 114] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 115] <-  "KW"
  df$countrycit_num[df$countrycit_num == 116] <-  "KG"
  df$countrycit_num[df$countrycit_num == 117] <-  "LA"
  df$countrycit_num[df$countrycit_num == 118] <-  "LV"
  df$countrycit_num[df$countrycit_num == 119] <-  "LB"
  df$countrycit_num[df$countrycit_num == 120] <-  "LS"
  df$countrycit_num[df$countrycit_num == 121] <-  "LR"
  df$countrycit_num[df$countrycit_num == 122] <-  "LY"
  df$countrycit_num[df$countrycit_num == 123] <-  "LI"
  df$countrycit_num[df$countrycit_num == 124] <-  "LT"
  df$countrycit_num[df$countrycit_num == 125] <-  "LU"
  df$countrycit_num[df$countrycit_num == 126] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 127] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 128] <-  "MG"
  df$countrycit_num[df$countrycit_num == 129] <-  "MW"
  df$countrycit_num[df$countrycit_num == 130] <-  "MY"
  df$countrycit_num[df$countrycit_num == 131] <-  "MV"
  df$countrycit_num[df$countrycit_num == 132] <-  "ML"
  df$countrycit_num[df$countrycit_num == 133] <-  "MT"
  df$countrycit_num[df$countrycit_num == 134] <-  "MH"
  df$countrycit_num[df$countrycit_num == 135] <-  "MQ"
  df$countrycit_num[df$countrycit_num == 136] <-  "MR"
  df$countrycit_num[df$countrycit_num == 137] <-  "MU"
  df$countrycit_num[df$countrycit_num == 138] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 139] <-  "MX"
  df$countrycit_num[df$countrycit_num == 140] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 141] <-  "MD"
  df$countrycit_num[df$countrycit_num == 142] <-  "MC"
  df$countrycit_num[df$countrycit_num == 143] <-  "MN"
  df$countrycit_num[df$countrycit_num == 144] <-  "ME"
  df$countrycit_num[df$countrycit_num == 145] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 146] <-  "MA"
  df$countrycit_num[df$countrycit_num == 147] <-  "MZ"
  df$countrycit_num[df$countrycit_num == 148] <-  "MM"
  df$countrycit_num[df$countrycit_num == 149] <-  "NA"
  df$countrycit_num[df$countrycit_num == 150] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 151] <-  "NP"
  df$countrycit_num[df$countrycit_num == 152] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 154] <-  "NC"
  df$countrycit_num[df$countrycit_num == 155] <-  "NZ"
  df$countrycit_num[df$countrycit_num == 156] <-  "NI"
  df$countrycit_num[df$countrycit_num == 157] <-  "NE"
  df$countrycit_num[df$countrycit_num == 158] <-  "NG"
  df$countrycit_num[df$countrycit_num == 159] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 160] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 161] <-  "MP"
  df$countrycit_num[df$countrycit_num == 162] <-  "NO"
  df$countrycit_num[df$countrycit_num == 163] <-  "OM"
  df$countrycit_num[df$countrycit_num == 164] <-  "PK"
  df$countrycit_num[df$countrycit_num == 165] <-  "PW"
  df$countrycit_num[df$countrycit_num == 240] <-  "PS"
  df$countrycit_num[df$countrycit_num == 166] <-  "PA"
  df$countrycit_num[df$countrycit_num == 167] <-  "PG"
  df$countrycit_num[df$countrycit_num == 168] <-  "PY"
  df$countrycit_num[df$countrycit_num == 169] <-  "PE"
  df$countrycit_num[df$countrycit_num == 170] <-  "PH"
  df$countrycit_num[df$countrycit_num == 171] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 172] <-  "PL"
  df$countrycit_num[df$countrycit_num == 173] <-  "PT"
  df$countrycit_num[df$countrycit_num == 174] <-  "PR"
  df$countrycit_num[df$countrycit_num == 175] <-  "QA"
  df$countrycit_num[df$countrycit_num == 176] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 177] <-  "RO"
  df$countrycit_num[df$countrycit_num == 178] <-  "RU"
  df$countrycit_num[df$countrycit_num == 179] <-  "RW"
  df$countrycit_num[df$countrycit_num == 180] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 181] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 182] <-  "LC"
  df$countrycit_num[df$countrycit_num == 183] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 184] <-  "VC"
  df$countrycit_num[df$countrycit_num == 185] <-  "WS"
  df$countrycit_num[df$countrycit_num == 186] <-  "SM"
  df$countrycit_num[df$countrycit_num == 187] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 188] <-  "SA"
  df$countrycit_num[df$countrycit_num == 189] <-  "SN"
  df$countrycit_num[df$countrycit_num == 241] <-  "RS"
  df$countrycit_num[df$countrycit_num == 190] <-  "SC"
  df$countrycit_num[df$countrycit_num == 191] <-  "SL"
  df$countrycit_num[df$countrycit_num == 192] <-  "SG"
  df$countrycit_num[df$countrycit_num == 193] <-  "SK"
  df$countrycit_num[df$countrycit_num == 194] <-  "SI"
  df$countrycit_num[df$countrycit_num == 195] <-  "SB"
  df$countrycit_num[df$countrycit_num == 196] <-  "SO"
  df$countrycit_num[df$countrycit_num == 197] <-  "ZA"
  df$countrycit_num[df$countrycit_num == 198] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 199] <-  "SS"
  df$countrycit_num[df$countrycit_num == 200] <-  "ES"
  df$countrycit_num[df$countrycit_num == 201] <-  "LK"
  df$countrycit_num[df$countrycit_num == 202] <-  "SD"
  df$countrycit_num[df$countrycit_num == 203] <-  "SR"
  df$countrycit_num[df$countrycit_num == 204] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 205] <-  "SZ"
  df$countrycit_num[df$countrycit_num == 206] <-  "SE"
  df$countrycit_num[df$countrycit_num == 207] <-  "CH"
  df$countrycit_num[df$countrycit_num == 208] <-  "SY"
  df$countrycit_num[df$countrycit_num == 209] <-  "TW"
  df$countrycit_num[df$countrycit_num == 210] <-  "TJ"
  df$countrycit_num[df$countrycit_num == 211] <-  "TZ"
  df$countrycit_num[df$countrycit_num == 212] <-  "TH"
  df$countrycit_num[df$countrycit_num == 153] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 213] <-  "TG"
  df$countrycit_num[df$countrycit_num == 214] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 215] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 216] <-  "TT"
  df$countrycit_num[df$countrycit_num == 217] <-  "TN"
  df$countrycit_num[df$countrycit_num == 218] <-  "TR"
  df$countrycit_num[df$countrycit_num == 219] <-  "TM"
  df$countrycit_num[df$countrycit_num == 220] <-  "TC"
  df$countrycit_num[df$countrycit_num == 221] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 222] <-  "UG"
  df$countrycit_num[df$countrycit_num == 223] <-  "UA"
  df$countrycit_num[df$countrycit_num == 224] <-  "AE"
  df$countrycit_num[df$countrycit_num == 225] <-  "GB"
  df$countrycit_num[df$countrycit_num == 226] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 227] <-  "UY"
  df$countrycit_num[df$countrycit_num == 228] <-  "UZ"
  df$countrycit_num[df$countrycit_num == 229] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 230] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 231] <-  "VE"
  df$countrycit_num[df$countrycit_num == 232] <-  "VN"
  df$countrycit_num[df$countrycit_num == 233] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 234] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 235] <-  "NULL"
  df$countrycit_num[df$countrycit_num == 236] <-  "YE"
  df$countrycit_num[df$countrycit_num == 238] <-  "ZM"
  df$countrycit_num[df$countrycit_num == 239] <-  "ZW"
  
  
  df$countryres_num[df$countryres_num == 1] <-  "US"
  df$countryres_num[df$countryres_num == 2] <-  "AF"
  df$countryres_num[df$countryres_num == 3] <-  "AL"
  df$countryres_num[df$countryres_num == 4] <-  "DZ"
  df$countryres_num[df$countryres_num == 5] <-  "AS"
  df$countryres_num[df$countryres_num == 6] <-  "AD"
  df$countryres_num[df$countryres_num == 7] <-  "AO"
  df$countryres_num[df$countryres_num == 8] <-  "AI"
  df$countryres_num[df$countryres_num == 9] <-  "NULL"
  df$countryres_num[df$countryres_num == 10] <-  "AG"
  df$countryres_num[df$countryres_num == 11] <-  "AR"
  df$countryres_num[df$countryres_num == 12] <-  "AM"
  df$countryres_num[df$countryres_num == 13] <-  "AW"
  df$countryres_num[df$countryres_num == 14] <-  "AU"
  df$countryres_num[df$countryres_num == 15] <-  "AT"
  df$countryres_num[df$countryres_num == 16] <-  "AZ"
  df$countryres_num[df$countryres_num == 17] <-  "BS"
  df$countryres_num[df$countryres_num == 18] <-  "BH"
  df$countryres_num[df$countryres_num == 19] <-  "BD"
  df$countryres_num[df$countryres_num == 20] <-  "BB"
  df$countryres_num[df$countryres_num == 21] <-  "BY"
  df$countryres_num[df$countryres_num == 22] <-  "BE"
  df$countryres_num[df$countryres_num == 23] <-  "BZ"
  df$countryres_num[df$countryres_num == 24] <-  "BJ"
  df$countryres_num[df$countryres_num == 25] <-  "BM"
  df$countryres_num[df$countryres_num == 26] <-  "BT"
  df$countryres_num[df$countryres_num == 27] <-  "BO"
  df$countryres_num[df$countryres_num == 28] <-  "BA"
  df$countryres_num[df$countryres_num == 29] <-  "BW"
  df$countryres_num[df$countryres_num == 30] <-  "NULL"
  df$countryres_num[df$countryres_num == 31] <-  "BR"
  df$countryres_num[df$countryres_num == 32] <-  "NULL"
  df$countryres_num[df$countryres_num == 33] <-  "BN"
  df$countryres_num[df$countryres_num == 34] <-  "BG"
  df$countryres_num[df$countryres_num == 35] <-  "BF"
  df$countryres_num[df$countryres_num == 36] <-  "BI"
  df$countryres_num[df$countryres_num == 37] <-  "KH"
  df$countryres_num[df$countryres_num == 38] <-  "CM"
  df$countryres_num[df$countryres_num == 39] <-  "CA"
  df$countryres_num[df$countryres_num == 40] <-  "CV"
  df$countryres_num[df$countryres_num == 41] <-  "KY"
  df$countryres_num[df$countryres_num == 42] <-  "CF"
  df$countryres_num[df$countryres_num == 43] <-  "TD"
  df$countryres_num[df$countryres_num == 44] <-  "CL"
  df$countryres_num[df$countryres_num == 45] <-  "CN"
  df$countryres_num[df$countryres_num == 46] <-  "NULL"
  df$countryres_num[df$countryres_num == 47] <-  "NULL"
  df$countryres_num[df$countryres_num == 48] <-  "CO"
  df$countryres_num[df$countryres_num == 49] <-  "KM"
  df$countryres_num[df$countryres_num == 50] <-  "CG"
  df$countryres_num[df$countryres_num == 51] <-  "NULL"
  df$countryres_num[df$countryres_num == 52] <-  "CK"
  df$countryres_num[df$countryres_num == 53] <-  "CR"
  df$countryres_num[df$countryres_num == 54] <-  "NULL"
  df$countryres_num[df$countryres_num == 55] <-  "NULL"
  df$countryres_num[df$countryres_num == 56] <-  "CU"
  df$countryres_num[df$countryres_num == 57] <-  "CY"
  df$countryres_num[df$countryres_num == 58] <-  "CZ"
  df$countryres_num[df$countryres_num == 59] <-  "DK"
  df$countryres_num[df$countryres_num == 60] <-  "DJ"
  df$countryres_num[df$countryres_num == 61] <-  "DM"
  df$countryres_num[df$countryres_num == 62] <-  "DO"
  df$countryres_num[df$countryres_num == 63] <-  "NULL"
  df$countryres_num[df$countryres_num == 64] <-  "EC"
  df$countryres_num[df$countryres_num == 65] <-  "EG"
  df$countryres_num[df$countryres_num == 66] <-  "SV"
  df$countryres_num[df$countryres_num == 67] <-  "GQ"
  df$countryres_num[df$countryres_num == 68] <-  "ER"
  df$countryres_num[df$countryres_num == 69] <-  "EE"
  df$countryres_num[df$countryres_num == 70] <-  "ET"
  df$countryres_num[df$countryres_num == 71] <-  "NULL"
  df$countryres_num[df$countryres_num == 72] <-  "NULL"
  df$countryres_num[df$countryres_num == 73] <-  "NULL"
  df$countryres_num[df$countryres_num == 74] <-  "FI"
  df$countryres_num[df$countryres_num == 75] <-  "FR"
  df$countryres_num[df$countryres_num == 76] <-  "GF"
  df$countryres_num[df$countryres_num == 77] <-  "PF"
  df$countryres_num[df$countryres_num == 78] <-  "NULL"
  df$countryres_num[df$countryres_num == 79] <-  "GA"
  df$countryres_num[df$countryres_num == 80] <-  "GM"
  df$countryres_num[df$countryres_num == 81] <-  "GE"
  df$countryres_num[df$countryres_num == 82] <-  "DE"
  df$countryres_num[df$countryres_num == 83] <-  "GH"
  df$countryres_num[df$countryres_num == 84] <-  "GI"
  df$countryres_num[df$countryres_num == 85] <-  "GR"
  df$countryres_num[df$countryres_num == 86] <-  "GL"
  df$countryres_num[df$countryres_num == 87] <-  "GD"
  df$countryres_num[df$countryres_num == 88] <-  "GP"
  df$countryres_num[df$countryres_num == 89] <-  "GU"
  df$countryres_num[df$countryres_num == 90] <-  "GT"
  df$countryres_num[df$countryres_num == 91] <-  "GN"
  df$countryres_num[df$countryres_num == 92] <-  "GW"
  df$countryres_num[df$countryres_num == 93] <-  "GY"
  df$countryres_num[df$countryres_num == 94] <-  "HT"
  df$countryres_num[df$countryres_num == 95] <-  "NULL"
  df$countryres_num[df$countryres_num == 96] <-  "HN"
  df$countryres_num[df$countryres_num == 97] <-  "NULL"
  df$countryres_num[df$countryres_num == 98] <-  "HU"
  df$countryres_num[df$countryres_num == 99] <-  "IS"
  df$countryres_num[df$countryres_num == 100] <-  "IN"
  df$countryres_num[df$countryres_num == 101] <-  "ID"
  df$countryres_num[df$countryres_num == 102] <-  "IR"
  df$countryres_num[df$countryres_num == 103] <-  "IQ"
  df$countryres_num[df$countryres_num == 104] <-  "IE"
  df$countryres_num[df$countryres_num == 105] <-  "IL"
  df$countryres_num[df$countryres_num == 106] <-  "IT"
  df$countryres_num[df$countryres_num == 107] <-  "JM"
  df$countryres_num[df$countryres_num == 108] <-  "JP"
  df$countryres_num[df$countryres_num == 109] <-  "JO"
  df$countryres_num[df$countryres_num == 110] <-  "KZ"
  df$countryres_num[df$countryres_num == 111] <-  "KE"
  df$countryres_num[df$countryres_num == 112] <-  "KI"
  df$countryres_num[df$countryres_num == 113] <-  "KR"
  df$countryres_num[df$countryres_num == 114] <-  "NULL"
  df$countryres_num[df$countryres_num == 115] <-  "KW"
  df$countryres_num[df$countryres_num == 116] <-  "KG"
  df$countryres_num[df$countryres_num == 117] <-  "LA"
  df$countryres_num[df$countryres_num == 118] <-  "LV"
  df$countryres_num[df$countryres_num == 119] <-  "LB"
  df$countryres_num[df$countryres_num == 120] <-  "LS"
  df$countryres_num[df$countryres_num == 121] <-  "LR"
  df$countryres_num[df$countryres_num == 122] <-  "LY"
  df$countryres_num[df$countryres_num == 123] <-  "LI"
  df$countryres_num[df$countryres_num == 124] <-  "LT"
  df$countryres_num[df$countryres_num == 125] <-  "LU"
  df$countryres_num[df$countryres_num == 126] <-  "NULL"
  df$countryres_num[df$countryres_num == 127] <-  "NULL"
  df$countryres_num[df$countryres_num == 128] <-  "MG"
  df$countryres_num[df$countryres_num == 129] <-  "MW"
  df$countryres_num[df$countryres_num == 130] <-  "MY"
  df$countryres_num[df$countryres_num == 131] <-  "MV"
  df$countryres_num[df$countryres_num == 132] <-  "ML"
  df$countryres_num[df$countryres_num == 133] <-  "MT"
  df$countryres_num[df$countryres_num == 134] <-  "MH"
  df$countryres_num[df$countryres_num == 135] <-  "MQ"
  df$countryres_num[df$countryres_num == 136] <-  "MR"
  df$countryres_num[df$countryres_num == 137] <-  "MU"
  df$countryres_num[df$countryres_num == 138] <-  "NULL"
  df$countryres_num[df$countryres_num == 139] <-  "MX"
  df$countryres_num[df$countryres_num == 140] <-  "NULL"
  df$countryres_num[df$countryres_num == 141] <-  "MD"
  df$countryres_num[df$countryres_num == 142] <-  "MC"
  df$countryres_num[df$countryres_num == 143] <-  "MN"
  df$countryres_num[df$countryres_num == 144] <-  "ME"
  df$countryres_num[df$countryres_num == 145] <-  "NULL"
  df$countryres_num[df$countryres_num == 146] <-  "MA"
  df$countryres_num[df$countryres_num == 147] <-  "MZ"
  df$countryres_num[df$countryres_num == 148] <-  "MM"
  df$countryres_num[df$countryres_num == 149] <-  "NA"
  df$countryres_num[df$countryres_num == 150] <-  "NULL"
  df$countryres_num[df$countryres_num == 151] <-  "NP"
  df$countryres_num[df$countryres_num == 152] <-  "NULL"
  df$countryres_num[df$countryres_num == 154] <-  "NC"
  df$countryres_num[df$countryres_num == 155] <-  "NZ"
  df$countryres_num[df$countryres_num == 156] <-  "NI"
  df$countryres_num[df$countryres_num == 157] <-  "NE"
  df$countryres_num[df$countryres_num == 158] <-  "NG"
  df$countryres_num[df$countryres_num == 159] <-  "NULL"
  df$countryres_num[df$countryres_num == 160] <-  "NULL"
  df$countryres_num[df$countryres_num == 161] <-  "MP"
  df$countryres_num[df$countryres_num == 162] <-  "NO"
  df$countryres_num[df$countryres_num == 163] <-  "OM"
  df$countryres_num[df$countryres_num == 164] <-  "PK"
  df$countryres_num[df$countryres_num == 165] <-  "PW"
  df$countryres_num[df$countryres_num == 240] <-  "PS"
  df$countryres_num[df$countryres_num == 166] <-  "PA"
  df$countryres_num[df$countryres_num == 167] <-  "PG"
  df$countryres_num[df$countryres_num == 168] <-  "PY"
  df$countryres_num[df$countryres_num == 169] <-  "PE"
  df$countryres_num[df$countryres_num == 170] <-  "PH"
  df$countryres_num[df$countryres_num == 171] <-  "NULL"
  df$countryres_num[df$countryres_num == 172] <-  "PL"
  df$countryres_num[df$countryres_num == 173] <-  "PT"
  df$countryres_num[df$countryres_num == 174] <-  "PR"
  df$countryres_num[df$countryres_num == 175] <-  "QA"
  df$countryres_num[df$countryres_num == 176] <-  "NULL"
  df$countryres_num[df$countryres_num == 177] <-  "RO"
  df$countryres_num[df$countryres_num == 178] <-  "RU"
  df$countryres_num[df$countryres_num == 179] <-  "RW"
  df$countryres_num[df$countryres_num == 180] <-  "NULL"
  df$countryres_num[df$countryres_num == 181] <-  "NULL"
  df$countryres_num[df$countryres_num == 182] <-  "LC"
  df$countryres_num[df$countryres_num == 183] <-  "NULL"
  df$countryres_num[df$countryres_num == 184] <-  "VC"
  df$countryres_num[df$countryres_num == 185] <-  "WS"
  df$countryres_num[df$countryres_num == 186] <-  "SM"
  df$countryres_num[df$countryres_num == 187] <-  "NULL"
  df$countryres_num[df$countryres_num == 188] <-  "SA"
  df$countryres_num[df$countryres_num == 189] <-  "SN"
  df$countryres_num[df$countryres_num == 241] <-  "RS"
  df$countryres_num[df$countryres_num == 190] <-  "SC"
  df$countryres_num[df$countryres_num == 191] <-  "SL"
  df$countryres_num[df$countryres_num == 192] <-  "SG"
  df$countryres_num[df$countryres_num == 193] <-  "SK"
  df$countryres_num[df$countryres_num == 194] <-  "SI"
  df$countryres_num[df$countryres_num == 195] <-  "SB"
  df$countryres_num[df$countryres_num == 196] <-  "SO"
  df$countryres_num[df$countryres_num == 197] <-  "ZA"
  df$countryres_num[df$countryres_num == 198] <-  "NULL"
  df$countryres_num[df$countryres_num == 199] <-  "SS"
  df$countryres_num[df$countryres_num == 200] <-  "ES"
  df$countryres_num[df$countryres_num == 201] <-  "LK"
  df$countryres_num[df$countryres_num == 202] <-  "SD"
  df$countryres_num[df$countryres_num == 203] <-  "SR"
  df$countryres_num[df$countryres_num == 204] <-  "NULL"
  df$countryres_num[df$countryres_num == 205] <-  "SZ"
  df$countryres_num[df$countryres_num == 206] <-  "SE"
  df$countryres_num[df$countryres_num == 207] <-  "CH"
  df$countryres_num[df$countryres_num == 208] <-  "SY"
  df$countryres_num[df$countryres_num == 209] <-  "TW"
  df$countryres_num[df$countryres_num == 210] <-  "TJ"
  df$countryres_num[df$countryres_num == 211] <-  "TZ"
  df$countryres_num[df$countryres_num == 212] <-  "TH"
  df$countryres_num[df$countryres_num == 153] <-  "NULL"
  df$countryres_num[df$countryres_num == 213] <-  "TG"
  df$countryres_num[df$countryres_num == 214] <-  "NULL"
  df$countryres_num[df$countryres_num == 215] <-  "NULL"
  df$countryres_num[df$countryres_num == 216] <-  "TT"
  df$countryres_num[df$countryres_num == 217] <-  "TN"
  df$countryres_num[df$countryres_num == 218] <-  "TR"
  df$countryres_num[df$countryres_num == 219] <-  "TM"
  df$countryres_num[df$countryres_num == 220] <-  "TC"
  df$countryres_num[df$countryres_num == 221] <-  "NULL"
  df$countryres_num[df$countryres_num == 222] <-  "UG"
  df$countryres_num[df$countryres_num == 223] <-  "UA"
  df$countryres_num[df$countryres_num == 224] <-  "AE"
  df$countryres_num[df$countryres_num == 225] <-  "GB"
  df$countryres_num[df$countryres_num == 226] <-  "NULL"
  df$countryres_num[df$countryres_num == 227] <-  "UY"
  df$countryres_num[df$countryres_num == 228] <-  "UZ"
  df$countryres_num[df$countryres_num == 229] <-  "NULL"
  df$countryres_num[df$countryres_num == 230] <-  "NULL"
  df$countryres_num[df$countryres_num == 231] <-  "VE"
  df$countryres_num[df$countryres_num == 232] <-  "VN"
  df$countryres_num[df$countryres_num == 233] <-  "NULL"
  df$countryres_num[df$countryres_num == 234] <-  "NULL"
  df$countryres_num[df$countryres_num == 235] <-  "NULL"
  df$countryres_num[df$countryres_num == 236] <-  "YE"
  df$countryres_num[df$countryres_num == 238] <-  "ZM"
  df$countryres_num[df$countryres_num == 239] <-  "ZW"
  ###End Matching Values from Codebook
  dfalp <- df[grepl(pattern="[[:alpha:]]", df$countrycit_num) & !grepl(pattern="[[:digit:]]", df$countryres_num), ]
  write.csv(dfdig, file.path(paste0("RaceIAT_public_",year,"_digit.csv")), row.names=FALSE, quote=FALSE)
  write.csv(dfalp, file.path(paste0("RaceIAT_public_",year,"_alpha.csv")), row.names=FALSE, quote=FALSE)
  #Deleting the old file to replace with the processed file
  fn <- file.path(paste0("Race IAT.public.",year,".csv"))
  if (file.exists(fn)) file.remove(fn)
  
  ###### Merging or mapping the files ######
  ## Processing the new format files
  datafile_year=paste0("RaceIAT_public_",year,"_digit.csv")
  df1 <- read.delim(file.path(Sys.getenv('my_dir'),'2021/05/impicit_racial_bias/original_european_map_of_implicit_racial_bias/data/Mapper.txt'))
  df11 <- read.delim(file.path(Sys.getenv('my_dir'),'2021/05/impicit_racial_bias/original_european_map_of_implicit_racial_bias/data/Ethnic.txt'))
  dfdig <- read.csv(datafile_year, header=TRUE)
  (map <- setNames(df1$countrycit_numcode, df1$countrycit_num))
  if (file.exists(fn)) file.remove(datafile_year)
  dfdig[c("countrycit_num", "countryres_num")] <- lapply(dfdig[c("countrycit_num", "countryres_num")],function(x) map[as.character(x)])
  ##race = White:6, ethnicity = White:5
  (map1 <- setNames(df11$ethniccode, df11$ethnic))
  dfdig[c("ethnicityomb")] <- lapply(dfdig[c("ethnicityomb")],function(x) map1[as.character(x)])
  fn<-file.path(datafile_year)
  if (file.exists(fn)) file.remove(fn)
}

new_format_years <- c(2017,2018,2019,2020)

for (i in new_format_years) {
  IAT_modern_format_2017_and_later(i)
}